name: Next.js Project CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Automated Tests (Jest)
    runs-on: ubuntu-latest 

    steps:
      - name: Code checkout
        uses: actions/checkout@v4 

      - name: Configure Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '20' 
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci 

      - name: Running Tests with Jest
        run: npm test 

  deploy: 
    name: Production Deployment for Vercel (Direct CLI)
    runs-on: ubuntu-latest
    needs: test 
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Vercel CLI and Project Dependencies
        run: |
          npm install --global vercel@latest
          npm ci 

      - name: Deploy with Vercel CLI
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} 
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
