name: CI/CD do Projeto Next.js

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Executar Testes Automatizados (Jest)
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 

      - name: Configurar Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '20' 
          cache: 'npm' 

      - name: Instalar dependências
        run: npm ci 

      - name: Rodar Testes com Jest
        run: npm test 

  deploy: 
    name: Deploy de Produção para Vercel (CLI Direto)
    runs-on: ubuntu-latest
    needs: test 
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Vercel CLI e Dependências do Projeto
        run: |
          npm install --global vercel@latest
          npm ci 

      - name: Fazer Deploy com Vercel CLI
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} 
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
